search:
  engine: opensearch / elasticsearch
  url: < URL:PORT >

logstash:
  replica: 1
  version: latest
  elasticUsername: 
  elasticPassword: 
  pipelines:
    - name: < container name >
      index: < search index >
      filter: < log parsing filters >

kibana:
  replica: 1
  version: 3.1.0
  elasticUsername: 
  elasticPassword: 
  logging:
    enabled: true

filebeat:
  enabled: true
  version: 8.19.6

ingress:
  enabled: true
  hosts:
    - search.database.local
