logstash:
  replica: 1
  version: latest
  elasticUsername: LOGSTASH_USERNAME
  elasticPassword: LOGSTASH_PASSWORD

kibana:
  replica: 1
  version: 3.1.0
  elasticUsername: KIBANA_USERNAME
  elasticPassword: KIBANA_PASSWORD

search:
  engine: opensearch / elasticsearch
  url: SEARCH_URL

ingress:
  enabled: true
  hosts:
    - search.database.local
