search:
  engine: opensearch / elasticsearch
  url: < URL:PORT >

logstash:
  replica: 1
  version: latest
  elasticUsername: 
  elasticPassword: 
  pipelines:
    - name: traefik
      index: "logs-ingress-traefik"
      filter: |
        mutate {
          copy => {
            "[kubernetes][labels][app_kubernetes_io/name]" => "app_name"
            "[kubernetes][namespace]"   => "namespace"
            "[kubernetes][pod][name]"   => "pod_name"
          }
        }

kibana:
  replica: 1
  version: 3.1.0
  elasticUsername: 
  elasticPassword: 

filebeat:
  enabled: true
  version: 8.19.6

ingress:
  enabled: true
  hosts:
    - search.database.local
