cluster:
  replicas: 1

storage:
  volumes:
    - name: config
      size: 2Gi
      path: /mnt/shared/jellyfin/config

ingress:
  enabled: true
  hosts:
    - jellyfin.media.local

logging:
  enabled: true
